### PR TITLE
Add PDFTeX support with New TX fonts

### PR DESCRIPTION
**Pull request by averms**
I'm not sure whether we should be using usepackage or RequirePackage. It seems like clsguide.pdf recommends the latter but it never explicitly advises against using the former? It's up to you, if you want I can change back to usepackage

### CODE REVIEW

**Comment by raxod502** [comment]
Thanks for the improvement. Would you mind letting me know what configuration this adds support for? To my knowledge PDFTeX already works fine.

**Comment by averms** [comment]
fontspec can't be used with PDFTeX. I replaced it with newtxtext if the engine is detected as PDFTeX. It is the best Times clone that is in CTAN and in Type 1 format (the credit for most of it should be given to the people at [GUST e-foundry](http://www.gust.org.pl/projects/e-foundry/tex-gyre/index_html)).

```
! Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex"instead of
(fontspec)                      "latex" or "pdflatex".

Type <return> to continue.
 ...                                              
                                                  
l.45 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
```

**Comment by raxod502** [comment]
Oops, you are right. I forgot that XeTeX was required. Once you update the README and CHANGELOG, I will be happy to merge.

**Comment by averms** [comment]
Updated.

**Review by raxod502 — APPROVED** [review]
I did some copyediting. Thanks for the contribution!

**Pull request merged**
