### PR TITLE
Add MLA enumeration

### PR DESCRIPTION
**Pull request by shepherdjerred**
I'm not terribly familiar with MLA or LaTeX, however I believe that this PR should make enumerations appear formatted correctly for MLA.

My use case is when creating an outline in the MLA style. I found guidelines for an MLA outline [here](https://libguides.liberty.edu/c.php?g=564129&p=4781213)

Example LaTeX
> \begin{enumerate}
    \item Item 1
    \item Item 2
    \begin{enumerate}
        \item Item 3
        \item Item 4
        \begin{enumerate}
            \item Item 5
            \item Item 6
        \end{enumerate}
    \end{enumerate}
\end{enumerate}

Example output
Screenshot of typeset LaTeX

### CODE REVIEW

**Comment by raxod502** [comment]
I think that I would feel more comfortable if these changes only took effect inside a new environment called, e.g., `outline`. MLA doesn't recommend using enumerated lists in essays, but it does admit that sometimes they are useful, and I think that the convention in this case is to use Arabic numbering rather than roman numerals. I don't think we should change the default numbering to roman numerals globally.

What do you think?

**Comment by shepherdjerred** [comment]
I think the idea of a separate environment for outlines makes sense. Like I said I'm no expert when it comes to MLA, so I'll defer to your judgment.

Also, thanks so much for spending the time to create this! It's been very helpful to me these past couple days.

**Comment by raxod502** [comment]
Okay—in that case I think it should be sufficient to wrap your code in `\newenvironment`, as TeX command definitions are scoped to the containing environment.

Then the README and changelog would need to be updated to document the new feature.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)

**Pull request closed without merging**
